#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
eval "$(dbus-launch --sh-syntax --exit-with-session)"
export XDG_CURRENT_DESKTOP=XFCE
export DISPLAY=:1
export LANG=zh_CN.UTF-8
export LC_ALL=zh_CN.UTF-8
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export INPUT_METHOD=fcitx
export SDL_IM_MODULE=fcitx
export XDG_RUNTIME_DIR=/tmp/root-runtime
mkdir -p "$XDG_RUNTIME_DIR"
chmod 700 "$XDG_RUNTIME_DIR"
fcitx5 -d --disable=wayland &
exec startxfce4
